spring.application.name=ProjectSprintFrontend
# ===============================
# SERVER CONFIG
# ===============================
server.port=8082


# ===============================
# BACKEND API CONFIG
# ===============================
backend.base-url=http://localhost:8080


# ===============================
# THYMELEAF (optional tuning)
# ===============================
spring.thymeleaf.cache=false


# ===============================
# LOGGING (optional but helpful)
# ===============================
logging.level.org.springframework.web.client.RestTemplate=DEBUG